# frozen_string_literal: true

task :load_environment do
  require_relative './config/environment'
end

namespace :lognalistics do
  namespace :total_views do
    task task: :load_environment do
      puts '--- Running total views statistics --- '
      processor = Lognalistics::Processor.new
      processor.generate_statistics('webserver.log', :total_views, :stdout)
    end
  end

  namespace :unique_views do
    task task: :load_environment do
      puts '--- Running unique views statistics --- '
      processor = Lognalistics::Processor.new
      processor.generate_statistics('webserver.log', :unique_views, :stdout)
    end
  end
end
